// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaCWAC_K_UKBV-S1j4uEFEzwkJ6Qne9O4',
    appId: '1:273435677923:web:5cd4ad989e9784fa9361d6',
    messagingSenderId: '273435677923',
    projectId: 'bccf-632b1',
    authDomain: 'bccf-632b1.firebaseapp.com',
    storageBucket: 'bccf-632b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSF_uDkmrKxwYIuwagxNhyTllH4d0zgPs',
    appId: '1:273435677923:android:d1c946bf706b87ca9361d6',
    messagingSenderId: '273435677923',
    projectId: 'bccf-632b1',
    storageBucket: 'bccf-632b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAae5mD7BMdVptbpyhRYDGF9ogVbaA99Vo',
    appId: '1:273435677923:ios:40defedb852f643b9361d6',
    messagingSenderId: '273435677923',
    projectId: 'bccf-632b1',
    storageBucket: 'bccf-632b1.appspot.com',
    iosClientId: '273435677923-3b6k0uscehlpdfr42j3sqkef30rrsms1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAae5mD7BMdVptbpyhRYDGF9ogVbaA99Vo',
    appId: '1:273435677923:ios:853924bc029183909361d6',
    messagingSenderId: '273435677923',
    projectId: 'bccf-632b1',
    storageBucket: 'bccf-632b1.appspot.com',
    iosClientId: '273435677923-8lnqhfms2bq7e20dbn2m16haeq2f0l9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
